name: "QA"

on:
  pull_request:
    branches: [ master, stable-* ]

permissions:
  pull-requests: write
  contents: read

concurrency: 
  group: qa-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3
      - name: set up JDK 17
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Install NDK and cmake
        run: |
          source ndk.env
          /usr/local/lib/android/sdk/tools/bin/sdkmanager "ndk;${NDK_VERSION}" "cmake;${CMAKE_VERSION}"
      - name: Build QA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p $HOME/.gradle
          echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
          sed -i "/qa/,/\}/ s/versionCode .*/versionCode ${{github.event.number}} /" app/build.gradle
          sed -i "/qa/,/\}/ s/versionName .*/versionName \"${{github.event.number}}\"/" app/build.gradle
          ./gradlew assembleQaDebug

      - name: Upload release assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          file: "app/build/outputs/apk/qa/debug/qa-debug-*.apk"
          overwrite: true
          branches: "run-workflows"
          verbose: true
          prerelease: true
          default_release_name: "Test release"
